### ISSUE TITLE
MacOS install latest gives an http 403 error

### ISSUE THREAD

**Issue by wc-zach** [kaizhu256/emsdk_portable#1]
When I try and do a simple install of the latest emsdk on MacOS I get an http 403: forbidden error. The steps to reproduce are quite simple:

```
:$ ./emsdk update
HTTP error with URL 'https://s3.amazonaws.com/mozilla-games/emscripten/packages/emsdk_unix_update.tar.gz': HTTP Error 403: Forbidden
Fetching all tags from Emscripten Github repository...
Done. 180 tagged releases available, latest is 1.39.3.
:$ ./emsdk install latest
Installing SDK 'sdk-1.35.0-64bit'..
Installing tool 'clang-e1.35.0-64bit'..
HTTP error with URL 'https://s3.amazonaws.com/mozilla-games/emscripten/packages/emscripten-clang_e1.35.0.tar.gz': HTTP Error 403: Forbidden
Installation failed!
```

If I try and fetch the resources manually with wget, curl or a web browser I also get the same error, which appears to be coming from AWS S3.

Thanks for any help you can give me in this matter.

**Comment by kaizhu256** [comment]
hihi, looks like whoever admin'd the s3 blobs:

https://s3.amazonaws.com/mozilla-games/emscripten/packages/emsdk_unix_update.tar.gz
https://s3.amazonaws.com/mozilla-games/emscripten/packages/emscripten-clang_e1.35.0.tar.gz

have disabled them.  i don't have control over that, and this repo is mostly unmaintained now :`(

**Comment by wc-zach** [comment]
Yes, I was afraid of that. It looks like the unix versions are still up, for now...
